### ISSUE TITLE
Ricette in conflitto: cartello d'acciaio e martello del fabbro

### ISSUE THREAD

**Issue by H4mlet** [MinetestItalia/minetest_italia#2]
Ho aperto una [richiesta di aggiornamento](https://github.com/minetest-mods/anvil/pull/10) del modulo anvil per risolvere il conflitto.

@peppinoita @pandaro

**Comment by peppinoita** [comment]
Mi sembrava di averlo già sistemato tempo fa. Poi controllo

**Comment by peppinoita** [comment]
Io lo avevo sistemato cosi':

`minetest.register_craft({
	output = "anvil:hammer",
	recipe = {
                {"default:steel_ingot","default:steel_ingot","default:steel_ingot"},
                {"default:steel_ingot","group:stick","default:steel_ingot"},
                {'',                   "group:stick",      ''                   } }
})
`

Che dici?

**Comment by H4mlet** [comment]
Mi sembra che vada bene: è intuitivo da ricordare e semplice da assemblare.

**Comment by peppinoita** [comment]
ok chiudo
