### ISSUE TITLE
Nodi alti irraggiungibili

### ISSUE THREAD

**Issue by H4mlet** [MinetestItalia/minetest_italia#3]
Penso in particolar modo a quelli degli alberi come le sequoie e le querce.
Ma anche alla difficoltà di costruire grandi strutture, senza potere volare.

Come soluzione propongo l'aggiunta del modulo [scaffolding](https://forum.minetest.net/viewtopic.php?f=11&t=3205&hilit=scaffolding) ("impalcatura") al server: funzionano come le scale ma sono nodi quadrati che permettono di creare piattaforme su cui camminare; utili sia per ripulire alberi alti che per costruire soffitti, torri, ecc.

**Comment by pandaro** [comment]
beh, mi sembra perfetto
potremmo pensare anche a deibonus per chi tiene pulito

**Comment by peppinoita** [comment]
Interessante, ma la mod e' del 2014.
Sara' compatibile? pandaro riesci a controllare il codice? (dovrebbe essere molto semplice visto che aggiunge solo un nodo).

**Comment by H4mlet** [comment]
L'ho provata in locale sul Minetest Game e in Hamlet's Quest, nessun problema riscontrato.
Una doppia verifica, però, non guasta.

**Comment by pandaro** [comment]
appena testato, no problem per me via libera
