### ISSUE TITLE
Tempo atmosferico noioso

### ISSUE THREAD

**Issue by H4mlet** [MinetestItalia/minetest_italia#4]
Sempre sole, sempre sereno.

Propongo l'aggiunta del modulo [snowdrift](https://github.com/paramat/snowdrift) per abbellire il server con neve e pioggia.

**Comment by pandaro** [comment]
potrebbe essere computazionalmente pesantuccio, da provare

**Comment by peppinoita** [comment]
Avevo visto tempo fa una mod che simulava le stagioni.
Mi sembrava bella, cambiava i colori delle foglie e la durata del giorno e della notte in base alle stagioni.
Non la ritrovo piu'...

**Comment by H4mlet** [comment]
La mod a cui ti riferisci è [mymonths](https://forum.minetest.net/viewtopic.php?t=13639) di Don.
Attenzione al carico sul server per via del cambio delle foglie al passare delle stagioni.
