### ISSUE TITLE
xp framework

### ISSUE THREAD

**Issue by pandaro** [MinetestItalia/minetest_italia#5]
Dunque ho giust'appunto forkato minetest italia, ho dei dubbi procedurali sul lavoro di squadra in github:
io vorrei creare un ramo(branch) sperimentale da dedicare ad xp framework.
Come devo operare?
chi deve creare il ramo?
ad ogni modo io ho provato xp framework in locale su  minetest_italia e tutto mi pare girare, almeno di base e senza errori.
perdonate la mia ignoranza a riguardo

**Comment by H4mlet** [comment]
nessuno sa tutto, chiedendo si impara

- su GitHub fai il fork del rapository ufficiale di Minetest Italia
- sul tuo pc clona il tuo fork
- entra nella cartella e crea un nuovo ramo: git branch NomeRamo
- controlla la presenza del nuovo ramo: git branch
- vedrai che il ramo master è preceduto da un asterisco, questo indica su quale ramo stai lavorando
- passa al ramo di sviluppo: git checkout NomeRamo
- controlla di essere effettivamente sul ramo di sviluppo: git branch

a questo punto tutte le modifiche che farai verranno applicate a quel ramo

per caricare sul tuo repository GitHub solo il ramo di sviluppo devi fare: git push origin NomeRamo

a questo punto sul tuo repository GitHub sarà presente il nuovo ramo con le modifiche

da qui in poi sta a @peppinoita  creare un ramo di sviluppo sul repository ufficiale di Minetest Italia, in modo che dal tuo ramo di sviluppo tu possa chiedere un pull sul ramo di sviluppo del repository ufficiale

**Comment by pandaro** [comment]
allora questo è il mio branch sperimentale su xp
[xpframework](https://github.com/pandaro/minetest_italia/tree/xp)
