### ISSUE TITLE
Mob distanti, tenerli o no?

### ISSUE THREAD

**Issue by H4mlet** [MinetestItalia/minetest_italia#6]
Mi riferisco a quelli che compaiono dove non ci sono giocatori, non ho idea di quanto carico possano esercitare sul server ma... se non c'è nessuno in zona, perché tenerli?

E' possibile disattivarli aggiungendo a minetest.conf questo parametro:

remove_far_mobs = true

Cosa ne pensate? @peppinoita @pandaro

**Comment by pandaro** [comment]
Per me tutto ciò che è inutile va fatto sparire dal carico globale del server:
per me andrebbe anche limitato la tipologia ed il numero di mob di superficie, mi sembra ci siano topi, conigli, galline, cinghial,i pecore e mucche, mancano solo i due leocorni.
Mi sembra ci siano pochi mobs cattivi in superficie, e troppo cibo.

**Comment by H4mlet** [comment]
In parte sono daccordo, in parte no:

- sto costruendo una metropolitana, il cibo serve spesso perché scavando e costruendo la sazietà cala velocemente
- di mob cattivi ce ne sono molti di notte, quelli di terra e quelli degli alberi; spesso i nuovi giocatori che hanno la sfortuna di entrare quando è notte diventano carne da macello

insomma, non rischiamo di farlo diventare un survival troppo estremo ora che la media serale è di una decina di giocatori

**Comment by pandaro** [comment]
ok scusa, stamattina ero violento di mio, rileggendo il commento forse esageravo. comunque lo spawn va protetto dai mobs, bisogna fare in modo che mobs non ce ne siano.

**Comment by pandaro** [comment]
perchè l'hai chiusa? è risolta?

**Comment by H4mlet** [comment]
No ma penso abbia più senso aprire un pull request con la modifica necessaria al file di configurazione; questa però influirebbe sul pull request della documentazione in gioco, perciò la farò dopo che quella sarà stata accettata o respinta.
